# Generated by Django 5.1.3 on 2024-11-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baixas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixa',
            name='valor_perda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
