# Generated by Django 5.1.3 on 2024-11-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_data_atualizacao_produto_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ean',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
