# Generated by Django 5.1.3 on 2024-11-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_fornecedor_produto_un_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ean',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='un_medida',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
