# Generated by Django 5.1.3 on 2024-11-11 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_cnpj_alter_fornecedor_telefone'),
        ('produtos', '0006_produto_foto_alter_produto_ean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor'),
        ),
    ]
