# Generated by Django 5.1.3 on 2024-11-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_cnpj_alter_fornecedor_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
