# Generated by Django 5.1.3 on 2024-11-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_fornecedor_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
