# Generated by Django 5.1.4 on 2024-12-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='photo',
        ),
    ]
