# Generated by Django 5.1.3 on 2024-11-14 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
