# Generated by Django 5.1.3 on 2024-11-12 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('tipo_transferencia', models.CharField(choices=[('revenda_to_avarias', 'Revenda para Avarias'), ('avarias_to_revenda', 'Avarias para Revenda')], max_length=20)),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('estoque_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques_destino', to='estoque.estoque')),
                ('estoque_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques_origem', to='estoque.estoque')),
            ],
        ),
    ]
