# Generated by Django 5.1.3 on 2024-11-12 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('transferencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='data_transferencia',
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='estoque_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='estoque.estoque'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='estoque_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origem', to='estoque.estoque'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='tipo_transferencia',
            field=models.CharField(choices=[('revenda_para_avarias', 'Revenda para Avarias'), ('avarias_para_revenda', 'Avarias para Revenda')], max_length=20),
        ),
    ]
