# Generated by Django 5.1.3 on 2024-11-12 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoque_produto'),
        ('transferencias', '0002_remove_transferencia_data_transferencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='estoque_destino',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='estoque_origem',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='estoque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.estoque'),
            preserve_default=False,
        ),
    ]
