# Generated by Django 5.1.3 on 2024-11-15 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0003_remove_transferencia_estoque_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='data_transferencia',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
