# Generated by Django 5.1.3 on 2024-11-12 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0004_fornecedor_ativo'),
        ('produtos', '0011_remove_produto_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_comprada', models.PositiveIntegerField()),
                ('data_compra', models.DateField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='fornecedores.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='produtos.produto')),
            ],
        ),
    ]
